### ISSUE TITLE
GoKoala Build Successful on Windows but Fails to Connect with GeoPackage

### ISSUE THREAD

**Issue by Youssef-Harby** [PDOK/gokoala#128]
I am trying to build GoKoala on Windows. Despite the build seemingly being successful, when I try to run:

```bash
./gokoala.exe --config-file ./examples/config_features_local.yaml --port 5050
2024/02/28 21:49:39 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2024/02/28 21:49:39 GoKoala - Cloud Native OGC APIs server, written in Go
2024/02/28 21:49:39 connected to local GeoPackage: examples\resources\addresses-crs84.gpkg
2024/02/28 21:49:39 failed to connect with GeoPackage: The specified module could not be found.
```

However, it works with:

```bash
./gokoala.exe --config-file ./examples/config_vectortiles.yaml --port 5050
2024/02/29 00:47:06 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2024/02/29 00:47:06 GoKoala - Cloud Native OGC APIs server, written in Go
2024/02/29 00:47:06 main server listening on http://0.0.0.0:5050
```

It seems there are issues related to SQLite/GeoPackage drivers or C/C++ packages. I built it on Windows 11 x64 in a Cygwin environment that has a C/C++ compiler and go v1.21.6, which I used before building [mbtileserver](https://github.com/consbio/mbtileserver?tab=readme-ov-file#development). Any help would be appreciated.

**Comment by rkettelerij** [comment]
Hi, thanks for your interest. I suspect the GeoPackage connection fails because it cannot find [SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index). Can you try:
- installing SpatiaLite
- (optionally) point the `SPATIALITE_LIBRARY_PATH` env variable to `/your/path/to/mod_spatialite`. 

If this is indeed the cause of the issue we should document this in the README.

**Comment by rkettelerij** [comment]
Also you could also try using the Docker container: `docker pull pdok/gokoala:latest`

**Comment by Youssef-Harby** [comment]
> Hi, thanks for your interest. I suspect the GeoPackage connection fails because it cannot find [SpatiaLite](https://www.gaia-gis.it/fossil/libspatialite/index). Can you try:
> 
>     * installing SpatiaLite
> 
>     * (optionally) point the `SPATIALITE_LIBRARY_PATH` env variable to `/your/path/to/mod_spatialite`.
> 
>     * Retry starting GoKoala with the `config_features_local.yaml` example.
> 
> 
> If this is indeed the cause of the issue we should document this in the README.

Thank you for the reply @rkettelerij ,
I installed SpatiaLite on Windows, I can see `"C:\Program Files\Spatialite\mod_spatialite.dll"`

<img width="852" alt="image" src="https://github.com/PDOK/gokoala/assets/13020265/82e0dbff-3d45-4fa2-a07f-d85b22126115">

and I can run:
```powershell
> spatialite
SpatiaLite version ..: 5.1.0    Supported Extensions:
        - 'VirtualShape'        [direct Shapefile access]
        - 'VirtualDbf'          [direct DBF access]
        - 'VirtualText'         [direct CSV/TXT access]
        - 'VirtualGeoJSON'              [direct GeoJSON access]
        - 'VirtualXL'           [direct XLS access]
        - 'VirtualNetwork'      [Dijkstra shortest path - obsolete]
        - 'RTree'               [Spatial Index - R*Tree]
        - 'MbrCache'            [Spatial Index - MBR cache]
        - 'VirtualFDO'          [FDO-OGR interoperability]
        - 'VirtualBBox'         [BoundingBox tables]
        - 'VirtualSpatialIndex' [R*Tree metahandler]
        - 'VirtualElementary'   [ElemGeoms metahandler]
        - 'VirtualRouting'      [Dijkstra shortest path - advanced]
        - 'VirtualKNN2' [K-Nearest Neighbors metahandler]
        - 'VirtualGPKG' [OGC GeoPackage interoperability]
        - 'VirtualXPath'        [XML Path Language - XPath]
        - 'SpatiaLite'          [Spatial SQL - OGC]
PROJ version ........: Rel. 9.2.1, June 1st, 2023
GEOS version ........: 3.12.0-CAPI-1.18.0
RTTOPO version ......: 1.1.0
TARGET CPU ..........: x86_64-w64-mingw32
the SPATIAL_REF_SYS table already contains some row(s)
SQLite version ......: 3.42.0
Enter ".help" for instructions
SQLite version 3.42.0 2023-05-16 12:36:15
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
```

I believe the issue is here because I tried to get some logs from driver loading here :
https://github.com/PDOK/gokoala/blob/c0658c26b3988ccf535807b4e0188963fa4acab5/ogc/features/datasources/geopackage/geopackage.go#L28-L44

My edit was
```go
const (
	sqliteDriverName = "sqlite3_with_extensions"
)

var once sync.Once

// Load sqlite (with extensions) once.
//
// Extensions are by default expected in /usr/lib. For spatialite you can
// alternatively/optionally set SPATIALITE_LIBRARY_PATH.
func loadDriver() {
	once.Do(func() {
		spatialite := os.Getenv("SPATIALITE_LIBRARY_PATH")
		println(spatialite)
		driver := &sqlite3.SQLiteDriver{Extensions: []string{spatialite}}
		wrappedDriver := sqlhooks.Wrap(driver, datasources.NewSQLLogFromEnv())
		if wrappedDriver == nil {
			println("Wrapped driver is nil")
		} else {
			log.Println("SQLite driver with extensions loaded successfully")
		}
	})
}
```

so when I run: 
```powershell
$env:SPATIALITE_LIBRARY_PATH = "C:\Program Files\Spatialite\"
go run .\main.go --config-file .\examples\config_features_local.yaml --port 5050
```
I get : 
```powershell
2024/02/29 13:20:48 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2024/02/29 13:20:48 GoKoala - Cloud Native OGC APIs server, written in Go
C:\Program Files\Spatialite
2024/02/29 13:20:48 SQLite driver with extensions loaded successfully
2024/02/29 13:20:48 failed to open GeoPackage: sql: unknown driver "sqlite3_with_extensions" (forgotten import?)
exit status 1
```

also when I try to change the sqliteDriverName to only "sqlite3" not "sqlite3_with_extensions"
I get : 
```powershell
2024/02/29 13:22:35 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
2024/02/29 13:22:35 GoKoala - Cloud Native OGC APIs server, written in Go
C:\Program Files\Spatialite
2024/02/29 13:22:35 SQLite driver with extensions loaded successfully
2024/02/29 13:22:35 connected to local GeoPackage: examples\resources\addresses-crs84.gpkg
2024/02/29 13:22:35 failed to connect with GeoPackage: no such function: spatialite_version
exit status 1
```
so it can be run with sqlite3 but without spatialite extensions so it can't run https://github.com/PDOK/gokoala/blob/c0658c26b3988ccf535807b4e0188963fa4acab5/ogc/features/datasources/geopackage/metadata.go#L25

Note that I am already using project examples

**Comment by rkettelerij** [comment]
> My edit was

Your edit is fine but you've removed the `sql.Register(sqliteDriverName, .....)` line. That's why you get a ` unknown driver "sqlite3_with_extensions"` error. It should start once you add that back.

**Comment by rkettelerij** [comment]
@Youssef-Harby did you get a change to try the suggestion from my last comment?

**Comment by Youssef-Harby** [comment]
@rkettelerij , thank you for the follow-up. I will try again today and let you know

**Comment by rkettelerij** [comment]
Can you post your code?

**Comment by Youssef-Harby** [comment]
@rkettelerij, Not a big thing to share .. Debugging and logging
